student:
    name: 陈强
    age: "18"
spring:
  freemarker:
    template-loader-path: classpath:/static
    request-context-attribute: request
    expose-request-attributes: true
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  # jdbc_config datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.129.25:3306/db_chenqiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: chenqiang
    password: a64500507z
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  devtools:                                 #热部署
    restart:
      additional-paths: springboot/src/main/java
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 2
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:Mappings/*.xml
  type-aliases-package: com.cq.springboot.Model
logging:
  config: classpath:logback-spring.xml