student:
    name: 陈强
    age: "18"
spring:
  mvc:
    view:
      prefix: views/
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8